name: Lambda Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - aws-deployment
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12
      - name: Build with Maven
        run: mvn package
      - name: Check for jar file
        run: |
          cd target/
          echo "target directory"
          ls
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          # Whether to set the AWS account ID for these credentials as a secret value, so that it is masked in logs. Valid values are 'true' and 'false'. Defaults to true
          mask-aws-account-id: true
      - name: deploy zip to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.FUNCTION_NAME }}
          zip_file: target/CardSystem-1.0-SNAPSHOT.jar
